### ISSUE TITLE
Too large amounts crash

### ISSUE THREAD

**Issue by Samasaur1** [Samasaur1/CityManagement#24]
**Describe the bug**
The game crashes when an amount is too large

**To Reproduce**
1. Type `buy food 1000000000000000`
2. See error

**Expected behavior**
The game should tell me I can't afford it, that I can afford it, or that I couldn't but went into debt

**Screenshots**
<img width="484" alt="screen shot 2018-07-02 at 5 40 12 pm" src="https://user-images.githubusercontent.com/30577766/42187716-ff7e9dee-7e1e-11e8-8fdc-f546b0d46a28.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Version: 0.7.2
 - Java vendor: Oracle
 - Java version: 1.8.0_131-b11

**Stack trace**
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "100000000000000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.samgauck.CityManagement.Command.buy(Command.java:114)
	at com.samgauck.CityManagement.Command.execute(Command.java:62)
	at com.samgauck.CityManagement.Main.main(Main.java:149)
```

**Additional context**
I don't know the size necessary, only that it is large

**Comment by Samasaur1** [comment]
I believe it stops working at a one with 10 zeros after it (i.e. `10000000000`), but that a one with 9 zeros after it (i.e. `1000000000`) works. That's what my testing showed

**Comment by Samasaur1** [comment]
In addition, the stack trace shows that it's a `NumberFormatException`, while I am **certain** that my formatting was correct. Perhaps `Integer.ParseInt` has a limit?

**Comment by Samasaur1** [comment]
It turns out that my failed values were out of `Integer` range. According to [this SO post](https://stackoverflow.com/questions/8030485/java-integer-parseint-failed-to-parse-a-string), I should use `Long.parseLong()` instead. However, I can just put a cap on the maximum amount at a time

**Comment by Samasaur1** [comment]
I think I'm just going to put a cap on it

**Comment by Samasaur1** [comment]
Although this brings up a good question: Should there be discounts for buying in bulk?

**Comment by Samasaur1** [comment]
Amounts in buying and selling still need to be redone

**Comment by Samasaur1** [comment]
Should be done now
