### ISSUE TITLE
Doesn't Open! 

### ISSUE THREAD

**Issue by drewarteaga** [Samasaur1/CityManagement#37]
### Describe the bug:
When I tried to run the file, it didn't work because there was a `NoClassDefFoundError`

### To Reproduce:
1. Download CItyManagement v0.8.1
2. Run `java -jar CityManagement-0.8.1.jar`

### Expected behavior:
The game should have started

### Screenshots:
![screen shot 2018-09-14 at 5 01 11 pm](https://user-images.githubusercontent.com/38357693/45574994-d6bd9800-b83f-11e8-8f73-fe41c4ff3465.png)

### Desktop (please complete the following information):
 - OS: macOS 10.13.1
 - Version: 0.8.1
 - Java vendor: Oracle
 - Java version: 1.8.0_161-b12

### Stack trace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/gauck/sam/Utilities/Utilities
	at com.samgauck.CityManagement.Economy.<init>(Economy.java:14)
	at com.samgauck.CityManagement.Economy.getInstance(Economy.java:29)
	at com.samgauck.CityManagement.Command.<init>(Command.java:23)
	at com.samgauck.CityManagement.Command.getInstance(Command.java:46)
	at com.samgauck.CityManagement.Main.<clinit>(Main.java:44)
Caused by: java.lang.ClassNotFoundException: com.gauck.sam.Utilities.Utilities
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

### Additional context:
It happened as soon as I tried to start it.

**Comment by Samasaur1** [comment]
Working on it

**Comment by Samasaur1** [comment]
This bug exists since 0.8.0, which is the first version when [Utilities](https://github.com/Samasaur1/Utilities) was external

**Comment by Samasaur1** [comment]
Utilities is not included in the JAR file, and so is not included in the class path.

Running:

```bash
java -cp path/to/CityManagement-0.8.1.jar:path/to/Utilities-1.4.0.jar com.samgauck.CityManagement.Main
```
will work

**Comment by Samasaur1** [comment]
If the `application` plugin is applied, then `gradle assembleDist` is run, a `zip` file and a `tar.gz` file are created
[CityManagement-0.8.1.zip](https://github.com/Samasaur1/CityManagement/files/2385146/CityManagement-0.8.1.zip)
